### ISSUE TITLE
Filter friends by created_at date range

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#102]
An admin viewing the Admin Friends index page should see an Advanced Search option to filter the Friends by created_at date.

**Comment by RunsWithBackpack** [comment]
Hey there! I just submitted a PR for this here: https://github.com/CZagrobelny/new_sanctuary_asylum/pull/112

Let me know if anything needs to be changed or of there's anything else I can do!

**Comment by CZagrobelny** [comment]
@RunsWithBackpack just merged!  Thank you for your work on this!
