### ISSUE TITLE
Unclear that 'Close Asylum Application' link is a link

### ISSUE THREAD

**Issue by GabiOC** [CZagrobelny/new_sanctuary_asylum#111]
The 'Close Asylum Application' link on the regional admin friends show page (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/regional_admin/friends/show.html.erb#L12) is confusing because it appears to be regular text but is actually a link. We should update it to be styled the same as the other links to ensure users know what it is.

**Screenshot**
<img width="1076" alt="screen shot 2018-08-03 at 2 29 59 pm" src="https://user-images.githubusercontent.com/8838416/43659404-ef02c6f6-9729-11e8-9a3a-cfa097de2dfa.png">

**Comment by GabiOC** [comment]
Hi @CZagrobelny , it looks like this is assigned but if no one's working on it, I can take it!

**Comment by CZagrobelny** [comment]
@GabiOC that would be great!  I think I only put the assigned label on it because I think we talked about you taking it, I don't remember, it's a blur.  But it's all yours!  Thank you!

**Comment by CZagrobelny** [comment]
Closing this because we plan to have a UX review of all the new functionality in the coming month.
