### ISSUE TITLE
Feature: An admin can note which users have 'Attended Training' 

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#121]
Background:  We have trainings on an ongoing basis for the pro se clinic and NSC admins want a checkbox on the user record to indicate that they have attended a training.

Database Changes:
- Add a column 'attended_training' to the users table (boolean)

Feature:
- On the admin user form, a Community Admin/Regional Admin should be able to edit a checkbox for the attended_training attribute.

**Comment by halfghaninne** [comment]
@CZagrobelny -- I'd love to take this ticket on if that's alright with you! I have blocks of time to work on this on Wednesday, Friday, and over the weekend.

**Comment by halfghaninne** [comment]
Thanks, @CZagrobelny ! An update -- I've run into a ruby versioning issue on my machine that's evading me (and rbenv). I'll let you know if I can't move past it and make meaningful progress by the end of this work week.

**Comment by CZagrobelny** [comment]
thanks @halfghaninne!  Happy to look at the ruby versioning issue if you aren't able to move past it this week!

**Comment by halfghaninne** [comment]
@CZagrobelny Thanks for your patience with me...I've been tied up with some exciting job things! I'm still stuck on this versioning issue. I just tried to re-clone the repo and the problem persists:

<img width="558" alt="screen shot 2018-10-30 at 11 25 13 am" src="https://user-images.githubusercontent.com/9288982/47729580-ce29f100-dc36-11e8-8d1a-fdacc27cdbcc.png">
<img width="523" alt="screen shot 2018-10-30 at 11 25 26 am" src="https://user-images.githubusercontent.com/9288982/47729608-da15b300-dc36-11e8-9b0b-23339c304462.png">

Would you have time this week to either meet up or hop on a video call to help figure this out? I'm really eager to regularly help out on this project but these set up issues really play to my frustrations/weaknesses!

**Comment by CZagrobelny** [comment]
@halfghaninne definitely!  I could do a video chat to debug Friday before like 4:30pm or sometime Sunday during the day if one of those options work well for you.  Thanks!

**Comment by CZagrobelny** [comment]
Just leaving this here as a note to self for when we start debugging: https://github.com/bundler/bundler/issues/4260

**Comment by CZagrobelny** [comment]
sweet! @halfghaninne does 4pm work for you?

**Comment by halfghaninne** [comment]
Yes, just sent you a calendar invite (I had a personal email for you from Rails Bridge)!

**Comment by CZagrobelny** [comment]
@halfghaninne deployed!  Thanks!!!
