### ISSUE TITLE
Cap accompaniment eligible activities

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#131]
Background
At the moment, we limit the number of accompaniments for activities that have the event attribute 'family_court'.  We want to be able to set a cap on accompaniments for activities with other types of events as well.

Implementation
We need to refactor the existing 'family_court' accompaniment cap so that is easily extensible to all accompaniment eligible activities.  I would propose moving the 'event' column on 'activities' to its own database table.  It could be renamed to something like 'activity_types', and could have columns 'name' and 'cap', allowing caps to be set on each type of activity individually.  We get requests to add a new activity type or add a 'cap' fairly frequently, so would be great if we were able to do this via the database, rather than needing a code change.

**Comment by CZagrobelny** [comment]
@yeti-detective thank you for laying it out like this, it is super helpful!
I am realizing, additionally, that the new table should also have a boolean 'accompaniment_eligible'.  That way we can leverage the association between an activity and activity_type (and the 'has_one' relationship you mentioned is exactly what I had in mind) to get activities that are either accompaniment_eligible or non_accompaniment_eligible.  After we set 'accompaniment_eligible' on each activity_type, we will be able to drop the 'events' column on the activities table. 

I have definitely written migrations that manipulate data after the column changes:  https://railsguides.net/change-data-in-migrations-like-a-boss/
My personal preference is to use a rake task or rails c because then I don't have to worry about issues with future users running a full db:migrate and hitting an error when they get to this migration due to the data structure or data in the database being different.

**Comment by yeti-detective** [comment]
Ok, I think if I just create a migration file & use ActiveRecord to iterate through Activities, setting the 'activity_type_id' to the matching `activity_type` then future devs will get the same effect in their databases when they run `db:migrate`

I'm pretty sure that's right.

**Comment by CZagrobelny** [comment]
Hi @yeti-detective !  I'm checking in with everyone who has an assigned issue to get a sense of eta for delivery, do you think you'll have time to get a PR ready for this issue by the end of the week (Sat.  Dec. 8)?  Thanks!

**Comment by yeti-detective** [comment]
Hi @CZagrobelny yes. I think I'm pretty near to closing this one. I was just on hiatus for the last week.

**Comment by CZagrobelny** [comment]
@yeti-detective merged and deployed!  Thank you so much for your work on this, it's hugely appreciated!
