### ISSUE TITLE
Fix 'Assigned Friends' field for Regional Admins editing a Remote Clinic Lawyer

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#135]
Context:  
We assign 'remote clinic' lawyers to friends so that they can view documents for the friend and add notes/instruction for the team filling out the documents remotely.  I have not documented the remote clinic flow yet, so it may be helpful to pair and talk through the flow before starting the story so that you know how to navigate to view these fields and what data needs to be in place.

The Issue:
We have a great select field for assigning lawyers to a friend:
<img width="861" alt="screen shot 2018-11-04 at 11 01 53 pm" src="https://user-images.githubusercontent.com/3056607/47977519-76501780-e086-11e8-8d5b-2d2adf6820ed.png">
Code is here: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/regional_admin/friends/show.html.erb#L60

BUT, the 'Assigned Friends' field is not working as desired.  We want the 'Assigned Friends' field, pictured here:
<img width="368" alt="screen shot 2018-11-04 at 11 02 07 pm" src="https://user-images.githubusercontent.com/3056607/47977563-c62ede80-e086-11e8-8734-2fd12442b378.png">
to use a chosen js select field, like 'Assigned Lawyers' above, so that we can display/add/remove multiple assigned friends.  Should also move it above the save button.
Current code: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/regional_admin/friends/show.html.erb#L60

**Comment by rsl** [comment]
work done on https://github.com/CZagrobelny/new_sanctuary_asylum/pull/138

**Comment by CZagrobelny** [comment]
@rsl thank you!!!  Merged!!!
