### ISSUE TITLE
User can use password reset if they don't remember their old password when prompted to change password

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#136]
We are using a Devise configuration to force every user to change their password every 3 months. Inevitably, many do not remember their old password when they go to change it...so they are stuck and I have to help them individually.

Would be AMAZING if they could simply do password reset (which we link to from the login page) to reset their password in this circumstance.  Password reset does not work when their user account is in this 'expired password' state, at the moment.

**Comment by rsl** [comment]
about to look into this

**Comment by rsl** [comment]
PR completed: https://github.com/CZagrobelny/new_sanctuary_asylum/pull/137

**Comment by CZagrobelny** [comment]
@rsl merged!  It works great, thank you so much for this!  I am SO looking forward to not getting all these emails about not being able to change passwords, this is really a dream!  You're the best ❤️
