### ISSUE TITLE
Add new volunteer types

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#139]
We want volunteer types to include French interpreter, Creole interpreter, K'iche' interpreter
They are defined here: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/models/user.rb#L13
The problem is that volunteer roles are enum.  We may add more types of interpreters after this, so enum is probably not the best choice.  Maybe we should switch to using strings for these.

**Comment by latazzajones** [comment]
@CZagrobelny can I take this?

**Comment by CZagrobelny** [comment]
@latazzajones I may close this one.  I think we need to re-evaluate the volunteer role options more, I need to check in with NSC about it...we've talked in the past about getting more detailed information from volunteers and/or letting them pick multiple languages or indicate that they know 'a little bit' of a language.  I am meeting with them on the 28th to start talking about the 2019 software priorities.

**Comment by latazzajones** [comment]
Cool - ya, my initial thoughs on this were to pull the types out into their own table which aligns with that. Let me know.
