### ISSUE TITLE
Add 'Border Crossing Status' to Friend Record

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#145]
Background
We want field to quickly see whether our friends are waiting to cross the border or have successfully crossed

Implementation
Add a database column 'border_crossing_status' (string) to the friends table.
Add a dropdown to edit this on the 'Basic' tab of the Admin Friend edit form below the 'Date of Entry' field. The options for the dropdown should be: 'Ready to Cross', 'Successfully Crossed'
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_basic_form_fields.html.erb

We should also display the state on this Friend show page:
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/f50d36a54e25d1b1601c45f88a37335afa9f49e3/app/views/friends/_info.html.erb

**Comment by halfghaninne** [comment]
Happy to take this on. Can give it high priority and quick attention.

**Comment by CZagrobelny** [comment]
@halfghaninne sorry, I completely missed this notification 5 days ago!

**Comment by CZagrobelny** [comment]
@halfghaninne let me know if you have capacity/want to work on this issue this week.  Thanks!

**Comment by halfghaninne** [comment]
@CZagrobelny also missed the notification 😂  I will have the capacity to work on this between Friday and Sunday.

**Comment by CZagrobelny** [comment]
@halfghaninne sweet!  We can check in Friday, see if it's still there.
