### ISSUE TITLE
Remote Clinic Lawyers should see phone numbers for all volunteers with access to the Friend

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#147]
*Background*
Remote Clinic Lawyers may need to contact volunteer team members with questions while they are reviewing the application, so we want to display their phone numbers.

*Implementation*
Display the phone numbers of each of the volunteers who worked on the draft here:  https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/remote_clinic/friends/show.html.erb#L19

**Comment by lavaturtle** [comment]
@CZagrobelny I'll take a look at this one.
