### ISSUE TITLE
All Email Notifications Sent In Remote Clinic Review Flow Should Contain a Link Directly to the Appropriate Page

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#149]
We want to include a link to the appropriate page in the following mailer methods:

ReviewMailer
*review_needed_email* => remote_clinic_friend_path(user_id: user_id, id: friend_id)
*lawyer_assignment_needed_email* => regional_admin_region_friend_path(region, friend)
*changes_requested* => community_friend_path(community.slug, friend)
*application_approved* => community_friend_path(community.slug, friend)

FriendshipAssignmentMailer
*send_assignment* => remote_clinic_friend_path(user_id: user_id, id: friend_id)

**We also want to remove community admins from the 'changes_requested' and 'application_approved' email.**

This video walkthrough shows all of these mailer methods in the context they are used: https://www.youtube.com/watch?v=hENKsdBYWEw

**Comment by kidatsy** [comment]
I can take a stab at this.

**Comment by CZagrobelny** [comment]
@kidatsy that would be awesome, thank you!  Marking it as 'assigned'!

**Comment by CZagrobelny** [comment]
@kidatsy thank you for this!  Merged the PR a while ago, but forgot to close the issue!
