### ISSUE TITLE
Add feature specs for Draft functionality

### ISSUE THREAD

**Issue by jmkoni** [CZagrobelny/new_sanctuary_asylum#158]
Right now, we have the ability for someone to [upload a draft](https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/drafts/_form.html.erb) to a specific friend record. There are two separate paths when you click 'Submit for Review' on a draft that we need to test:

- IF a remote clinic lawyer has been assigned to the friend, they will get notified
- IF a remote clinic lawyer has NOT been assigned to the friend, the regional admin is sent a notification to assign a remote clinic lawyer to the friend

For an overview of the full functionality: https://www.youtube.com/watch?v=hENKsdBYWEw

Possible way to deal with carrier wave in specs: https://til.codes/testing-carrierwave-file-uploads-with-rspec-and-factorygirl/

**Comment by lavaturtle** [comment]
@CZagrobelny I can work on this.

**Comment by CZagrobelny** [comment]
Thanks @lavaturtle!  Marking as assigned!  Let me know if you have questions, I anticipate that the uploading a file aspect of this will be challenging, I looked at it in the past, but didn't come up with a solution.

**Comment by lavaturtle** [comment]
I've finally submitted a PR for this. Sorry this took so incredibly long! I'll make sure next time I claim something that I can actually finish it quickly.

**Comment by CZagrobelny** [comment]
@lavaturtle thank you!!!  This is amazing, merged!  It will be so helpful to us in writing future specs as well!  Thank you!!!
