### ISSUE TITLE
Address Flappy Specs

### ISSUE THREAD

**Issue by latazzajones** [CZagrobelny/new_sanctuary_asylum#169]
There are some feature specs that are inconsistant on circle ci. See this build: https://circleci.com/gh/CZagrobelny/new_sanctuary_asylum/688?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Also - we should explore replacing FFaker with Faker since the latter is a much more robust library and addresses some of the causes of failures around uniqueness.

**Comment by jmkoni** [comment]
I'm going to create an issue to replace FFaker with Faker.

**Comment by latazzajones** [comment]
example of strange failure: https://circleci.com/gh/CZagrobelny/new_sanctuary_asylum/714?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by latazzajones** [comment]
Better example of flapping specs https://circleci.com/gh/CZagrobelny/new_sanctuary_asylum/727?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by latazzajones** [comment]
https://github.com/CZagrobelny/new_sanctuary_asylum/pull/186 attempts to deal with rspec ./spec/features/volunteer/accompanying_friends_spec.rb We'll see how it goes. 

There are a couple other specs that are flapping in https://circleci.com/gh/CZagrobelny/new_sanctuary_asylum/727?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link. We can address those after we see if https://github.com/CZagrobelny/new_sanctuary_asylum/pull/186 helps.

**Comment by CZagrobelny** [comment]
@latazzajones closing this, since I haven't seen much flapping in the past couple months! Thank you!!!!
