### ISSUE TITLE
Add outcome_of_hearing to Accompaniment Report

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#175]
Accompaniment leaders are able to add/edit an accompaniment report for the activities they attend.  We want to add a new text field on this report 'outcome_of_hearing'.

Here is the view file for the accompaniment report form: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/accompaniment_leader/accompaniment_reports/_form.html.erb

We also want to update the display of the accompaniment report to include the new field.  We display the accompaniment report in a few places:
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/54f43398228fab221042f97d3d2fd3421233c9d4/app/views/accompaniment_leader/activities/_accompaniment_modal.html.erb#L47
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/997a31124da74612e05cedac13f4446a8fd0d00d/app/views/admin/activities/_activity.html.erb#L35
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/54f43398228fab221042f97d3d2fd3421233c9d4/app/views/admin/friends/activities/_activity.html.erb#L29
For all of the above, let's change the display to:
<strong>Report Back by [insert report author name]:</strong>
<strong>Outcome of hearing:</strong> [insert outcome_of_hearing]
<strong>Notes: </strong> [insert notes]

Lastly, make sure that we have replaced the language 'Accompaniment Leader Notes' with 'Report Back' throughout the views in the codebase for consistency.

**Comment by CZagrobelny** [comment]
@latazzajones if you want to take this one!

**Comment by latazzajones** [comment]
- [ ] Add column to table
- [ ] Add field to form
- [ ] Update view admin/activities/_activity.html.erb and admin/friends/activities/_activity.html.erb
- [ ] Change "Accompaniment Leader Notes" to "Report Back" in codebase

**Comment by CZagrobelny** [comment]
Merged and deployed! Thank you!!!
