### ISSUE TITLE
Make Judge and Location drop downs searchable 

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#177]
We now have too many Judges and Locations and need to use the chosen js searchable dropdown rather than a normal dropdown.

Should just be a matter of finding all the collection_select for judges and locations, adding the class 'chzn-select' to each of them, and verifying that the change worked.

**Comment by emi1337** [comment]
I'm on this too!

**Comment by CZagrobelny** [comment]
Thank you @emi1337 !  Merged and deployed!!!
