### ISSUE TITLE
Add Jail ID for friends

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#179]
### Background
When friends are detained, we need to be able to store the id number they are issued by the jail.

### Implementation
- Add jail_id (string) to friends table
- Allow an admin to edit the jail_id for a friend (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_detention_form_fields.html.erb#L12)
- Display jail_id on friend show page (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/friends/_info.html.erb#L66)

**Comment by acaporrini** [comment]
@CZagrobelny I made a PR for this, thank you
