### ISSUE TITLE
Sort the user index in a more useful way.

### ISSUE THREAD

**Issue by latazzajones** [CZagrobelny/new_sanctuary_asylum#192]
As an admin viewing the user index page, I would like it to be sorted by date with the most recent first. It is currently sorted by the most recent last.

**Comment by rsl** [comment]
i peeked in to this and it seems to be sorting `created_at desc` on `Admin::UsersController#index`. is there a different page i should be looking at?

**Comment by CZagrobelny** [comment]
@rsl that's the right page...I'm interested if it can be re-created locally.  Here is a screenshot of part of the users table on production:
<img width="106" alt="screen shot 2019-03-01 at 11 22 06 am" src="https://user-images.githubusercontent.com/3056607/53651344-76b38600-3c14-11e9-941b-68e456b7fbec.png">
In addition to these not being in order, there were definitely users created this week and they're not at the top.

**Comment by rsl** [comment]
aha. i hadn't rebased that one on upstream yet. the filterrific changes must have changed what's there. easy peasy.

**Comment by CZagrobelny** [comment]
@rsl thank you!  Merging and deploying!
