### ISSUE TITLE
Devise password reset configuration change

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#195]
If a user who has not created an account (either they have no user account OR they have been invited but have not accepted the invitation and officially 'created' their user account) attempts to login, we should display a flash error message letting them know that they do not yet have an account.  At the moment the flash message says 'Invalid Email or Password'.
<img width="1051" alt="Screen Shot 2019-06-11 at 9 10 14 AM" src="https://user-images.githubusercontent.com/3056607/59275105-ae759500-8c29-11e9-8d05-f79291be91c0.png">

**Comment by yeti-detective** [comment]
Hi CZ, I'v been out of the picture for a minute, but wanted to see if I could jump back in. Is this issue still ongoing? I tried going to "forgot password" from the login screen, putting in a fake email, clicking the 'Send me...' button & got this:

![fake email dev](https://dl.dropbox.com/s/h8fr1cijpwqllwt/emailNotFound.png?dl=0)

**Comment by CZagrobelny** [comment]
@yeti-detective yay!  It's been a while since I added this issue, so I don't remember everything about the original reports of the issue.  You're right, the password reset one does display a message about the account not existing.
I'm going to edit the issue to focus on the login page, because I do remember getting confused/frustrated emails about that.  I had help off on changing the login behavior because it does potentially expose some information (the fact that an account at an email does/does not exist), but I think the trade off is worth it at this point.  At this point, we are locking accounts after too many unsuccessful logins and are throttling login attempts, which mitigates this vulnerability a bit.

**Comment by yeti-detective** [comment]
@CZagrobelny got it. I'll take up this issue on the login page, then. Do you want to just split up the messages to "invalid email address" if they're using an email address that isn't in the user table and "invalid password" if the email is valid, but the password is wrong?
Or we could be more explicit like, "No user account with that email address"

**Comment by CZagrobelny** [comment]
@yeti-detective I think "No user account with that email address" if the email isn't in the users table!  And the current error message 'Invalid Email or password' can stay in place for cases when the password is invalid.  Thanks!

**Comment by CZagrobelny** [comment]
@yeti-detective merged!  Thank you so much for this, will make it much easier to figure out what they need to do to sign up for accompaniments!
