### ISSUE TITLE
On Admin accompaniment calendar, display detained Friend activities in RED

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#201]
On Admin accompaniment calendar, accompaniment-eligible activities should be displayed in red IF the Friend is 'detained'.

## Implementation
This is the admin Accompaniments view:  https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/activities/accompaniments.html.erb
If the friend associated with the activity has a status: 'in_detention', then the link for the activity on the admin calendar should be red (rather than blue).
We're doing something similar (with different conditional logic) here: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/54f43398228fab221042f97d3d2fd3421233c9d4/app/views/accompaniment_leader/activities/index.html.erb#L15

We only want this behavior on the admin accompaniment calendar.

**Comment by emi1337** [comment]
I can take this one while I ramp up!

**Comment by CZagrobelny** [comment]
@emi1337 Thank you so much, just deployed!  They will be thrilled to have this, Janice was following up about it last week!
