### ISSUE TITLE
Improve Event Attendance UI

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#202]
1.  Display numbers [1-the total number of friends/volunteers attending] in a column next to the names of those attending.  This will allow us to quickly see how many people are attending each event.
2.  The names of Friends and Users in the table should link to the admin edit pages for the Friend or the User.  This will allow admins to navigate directly to the record from the attendance page.

## Implementation
This is the attendance page: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/events/attendance.html.erb

**Comment by emi1337** [comment]
I can take this next!

**Comment by emi1337** [comment]
Hey @CZagrobelny I was looking over the notes here and can't quite figure out where you want the attendance numbers to be. Can you send a screenshot or something?

You say " in a column next to the names of those attending", but the UI doesn't make sense with what I think that means. 

In the table next to the names here doesn't make sense as each row is just one person:
<img width="1137" alt="Screenshot 2019-04-02 01 16 54" src="https://user-images.githubusercontent.com/1188988/55377911-0a62c580-54e5-11e9-9b11-2ae42d281c76.png">

And in this view, there's no "names of those attending" column, so I'm a bit confused hahha.
<img width="1241" alt="Screenshot 2019-04-02 01 17 37" src="https://user-images.githubusercontent.com/1188988/55377978-4138db80-54e5-11e9-93f3-acaa9d6899c6.png">

**Comment by CZagrobelny** [comment]
@emi1337 yes! Sorry for the confusing description, I remember writing this issue now and describing that part was challenging.  Here's an image!
<img width="612" alt="55377911-0a62c580-54e5-11e9-9b11-2ae42d281c76" src="https://user-images.githubusercontent.com/3056607/55401988-49fad300-5520-11e9-9c90-598c1a80f838.png">

**Comment by emi1337** [comment]
ohhh, i see! thanks tons :D got it!

**Comment by CZagrobelny** [comment]
@emi1337 merged and deployed! Thank you!  This will make life easier for Sara, Melissa, and the volunteers checking Friends in at clinic!
