### ISSUE TITLE
Admins can filter Users by Role

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#203]
We want admins to be able to filter users by 'role'.  They should see a role dropdown containing a list of our role options (note: these are different for primary and non-primary communities), selecting a role should display only the users assigned to that role.  Ee are using the filterrific gem for filtering.  This is the admin users index page: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/users/index.html.erb

**Comment by emi1337** [comment]
I can do this one!

**Comment by CZagrobelny** [comment]
@emi1337 thank you so much for knocking this out, it's so useful for them in auditing user permissions!
