### ISSUE TITLE
Admin should be able to 'unconfirm' activities

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#205]
## Background
For accompaniment eligible activities (court dates, check ins), when the date is coming up, admins will call EIOR and make sure the court date/check in is still on at the scheduled time.  EIOR frequently cancels/reschedules court dates without notifying our Friends, so this is an important step.

## Feature
Sometimes admins 'confirm' an activity accidentally and there is no way to 'Unconfirm' it.  We should replace the 'Confirmed by Admin' text with a 'Unconfirm' button in a different color than the 'Confirm' button (maybe red).  This 'Unconfirm' button should set the 'confirmed' boolean on the activity to false.

**Comment by emi1337** [comment]
I can do this

**Comment by CZagrobelny** [comment]
@emi1337 merged and deployed!  Thank you, Sara will be so stoked to have this!
