### ISSUE TITLE
Track ‘intake date’ for Friends and allow admins to sort Friends by this date

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#206]
## Background
We need to be able to keep track of when Friends went through intake so that admins can sort by this date when putting together the cohorts for clinic.

## Implementation
- [ ] Add a new datetime column on Friends called ‘intake_date’
- [ ] An admin should be able to add/edit the ‘intake’ date on the ‘Clinic’ tab of the Friend edit page (we should use a javascript date picker, that shows the calendar rather than the year/month/day drop downs). Put this field at the top under a header, ‘Intake’.
- [ ] This info does NOT need to be displayed on the Friend ‘show’ pages that regular volunteers see, it’s just for admins
- [ ] On the Admin Friends index page, add the following sorting options/functionality to the sorting dropdown:  ‘Intake Date (Ascending)’, ‘Intake Date (Descending)’

Note: we are using the filterrific gem for sorting.

**Similar to this issue, probably most efficient for one developer to take both:** https://github.com/CZagrobelny/new_sanctuary_asylum/issues/207

**Comment by emi1337** [comment]
Can take these 2 next!

**Comment by CZagrobelny** [comment]
@emi1337 thank you!!!!
