### ISSUE TITLE
Track ‘must be seen by date’ for Friends and allow admins to sort Friends by this date

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#207]
## Background
When Friends go through intake, we need to be able to track if there is an upcoming deadline in their immigration case that requires them to come to clinic by a specific date.  When putting together the cohorts, we want to be able to sort by this date so that we can catch Friends whose date is coming up.

## Implementation
- [ ] Add a new datetime column on Friends called ‘must_be_seen_by’
- [ ] An admin should be able to add/edit the ‘must_be_seen_by’ date on the ‘Clinic’ tab of the Friend edit page (we should use a javascript date picker, that shows the calendar rather than the year/month/day drop downs). Put this field at the top, under an ‘Intake’ header
- [ ] This info does NOT need to be displayed on the Friend ‘show’ pages that regular volunteers see, it’s just for admins
- [ ] On the Admin Friends index page, add the following sorting option/functionality to the sorting dropdown:  ‘Must Be Seen By (Soonest)’

Note: we are using the filterrific gem for sorting.

**Similar to this issue, probably most efficient for one developer to take both:** https://github.com/CZagrobelny/new_sanctuary_asylum/issues/206

**Comment by emi1337** [comment]
Can take these 2 next!

**Comment by CZagrobelny** [comment]
@emi1337 thank you for knocking both of these out, this is so exciting!  QA'd them both and they work great!  You are the best!!!
