### ISSUE TITLE
An admin can add/edit intake notes for a Friend

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#208]
## Background
When Friends go through intake, we need to be able to add notes about the Friend’s case.

## Implementation
- [ ] Add a new text column on Friends called ‘intake_notes’
- [ ] An admin should be able to add/edit the ‘intake_notes’ field on the ‘Clinic’ tab of the Friend edit page.  Put this field at the top under an ‘Intake’ header.
- [ ] This info does NOT need to be displayed on the Friend ‘show’ pages that regular volunteers see, it’s just for admins

**Comment by emi1337** [comment]
I can take this :)

**Comment by CZagrobelny** [comment]
@emi1337 thank you!  QA'd and merged!
