### ISSUE TITLE
An admin can track ‘Clinic Wait List Priority’ for Friends and Filter/Sort Friends by ‘Clinic Wait List Priority’

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#209]
## Background
When we transition our weekly pro se clinic to assign Friends to a specific cohort, this waiting list prioritization system will be used by admins in selecting Friends for a cohort.

## Implementation
- [x] Add a new integer column ‘clinic_wait_list_priority’ to the Friends table (integer so we can use enums…which should allow us to sort Friends by priority order 🤞)
- [x] An admin should be able to add/edit the ‘clinic_wait_list_priority’ on the ‘Clinic’ tab of the Friend edit page.  This should be a select at the top of the page with 3 options: ‘Priority’, ‘Needs Attention’, ‘Can Wait’…plus a blank option.
- [x] This info does NOT need to be displayed on the Friend ‘show’ pages that regular volunteers see, it’s just for admins
- [x] On the Admin Friends index page, in the ‘ID’ column, add a flag icon with a color corresponding to the Friend’s clinic_wait_list_priority IF the Friend has a clinic_wait_list_priority selected.  Priority => Red, Needs Attention => Yellow, Can Wait => Green.  We are using font awesome, I’m sure they’ll have a nice flag icon.
- [x] Add filtering functionality on the Admin Friends index page to allow an admin to filter Friends by one or more ‘clinic_wait_list_priorities’.  For example, they might want to view all the Friends with ‘clinic_wait_list_priority’ either ‘Priority’ or ‘Needs Attention’. 
- [x] On the Admin Friends index page, add the following sorting option/functionality to the sorting dropdown:  ‘Clinic Wait List Priority (Highest)’, ‘Clinic Wait List Priority (Lowest)’

Note: we are using the filterrific gem for sorting.

**Comment by CZagrobelny** [comment]
@latazzajones would you be able to take this issue?

**Comment by latazzajones** [comment]
@CZagrobelny I can pick it up tonight.

**Comment by CZagrobelny** [comment]
@latazzajones do you think you'll have time to complete this one by the end of next weekend?  The FA All Staff retreat is this week, so am in no rush to get it sooner than end of next weekend.

**Comment by CZagrobelny** [comment]
This issue is available to pick up.

**Comment by emi1337** [comment]
I can take this next :)

**Comment by emi1337** [comment]
Okay this is done now! Sorry I had some delays--my computer had to be taken in by the Apple folks "genius bar" so I was out of commission for the a while.

**Comment by CZagrobelny** [comment]
Thank you @emi1337 !  This is merged and deployed along with the other PR of mine that I had hanging out there for a while, meaning that we made it across the finish line of our new clinic structure sprint! 🎉 🏆 Thank you so much for all of your work to make this happen! ❤️
