### ISSUE TITLE
Allow admins to sort Friends by 'date of entry'

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#210]
## Background
Date of entry is an important factor in prioritizing Friends for placement in clinic cohorts because asylum applications must be submitted within one year of their date of entry to the United States.

## Implementation
On the Admin Friends index page, add the following sorting options/functionality to the sorting dropdown:  ‘Date of Entry (Ascending)’, ‘Date of Entry (Descending)’

Note: we are using the filterrific gem for sorting.

**Comment by emi1337** [comment]
Can take this one!

**Comment by CZagrobelny** [comment]
@emi1337 QA'd and merged, everything is looking great!  THANK YOU!
