### ISSUE TITLE
Wrap 'submit_for_review' and 'approve' contents in a transaction block

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#227]
This line should be wrapped: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/controllers/drafts_controller.rb#L67

And this one: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/controllers/drafts_controller.rb#L79

**Comment by rsl** [comment]
hey @CZagrobelny i suspect this method could use a transaction too https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/controllers/reviews_controller.rb#L18

**Comment by CZagrobelny** [comment]
Merged, thank you!
