### ISSUE TITLE
Audit requests that are 'get' but should actually be 'post'

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#228]
One example is 'confirm'/'unconfirm' for activities.  As a starting point, would be good to pull together a list of links to them in github.

**Comment by rsl** [comment]
- `DraftsController#submit_for_review`
- `DraftsController#approve`
- `Admin::ActivitiesController#confirm`
- `Admin::ActivitiesController#unconfirm`
- `Admin::Friends::ActivitiesController#confirm`
- `Admin::Friends::ActivitiesController#unconfirm`
- `RegionalAdmin::ApplicationsController#close`

**Comment by rsl** [comment]
is this actionable for editing yet? i don't wanna jump the gun on it but just saw it again.

**Comment by CZagrobelny** [comment]
@rsl totally!  Thanks!

**Comment by CZagrobelny** [comment]
Merged!  Thank you!
