### ISSUE TITLE
Customize User Invitation Email with Community Name

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#242]
## Background
The application is multi-tenant, and we want the user invitation email to better reflect that.

## Implementation
Each community has a 'name' that distinguishes them, and we want these names displayed in the subject and body of the user invitation email.  When a user is created, they belong to a specific community.
Body of invitation email is here: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/devise/mailer/invitation_instructions.html.erb
And here: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/devise/mailer/invitation_instructions.text.erb

After 'New Sanctuary Coalition', we want to display the community name in parenthesis and ALL CAPS.  For example, if the community name is 'cbst', the email should look like:

SUBJECT: New Sanctuary Coalition (CBST) volunteer account invitation

BODY:
Welcome New Sanctuary Coalition (CBST) volunteer!

Please follow this link to accept your invitation to the New Sanctuary Coalition (CBST) software: https://new-sanctuary.herokuapp.com/users/communities/nyc/invitation/accept?invitation_token=2KUvHTPw7hi3x3Y-oyAR

This invitation will expire August 05, 2019 02:07 PM.

Creating an account will allow you to participate in the pro se clinic and accompaniment.

Please watch this short instructional video to learn how to set up an account, reset your password, and use the software for the accompaniment program and pro se ligal clinic.

If you don't want to accept the invitation, please ignore this email. Your account won't be created until you access the link above and set your password.

Thank you for all your hard work,

The New Sanctuary Coalition (CBST) team

**Comment by sansbrina** [comment]
I'd love to pick this one up!

**Comment by CZagrobelny** [comment]
@sansbrina thank you so much for this!  We were losing volunteers in one of our clinics because they didn't recognize their community name in the email, so having this customization means a lot less confusion and more volunteers!
