### ISSUE TITLE
Add EOIR case status

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#243]
## Background
Accompaniment program staff would like to be able to save an EOIR case status for a Friend.  This is the status of their immigration case, and knowing this information helps staff quickly assess how high-risk an accompaniment (to a court hearing or check-in with ICE) is.

## Implementation
- [ ] Add a new string column eior_case_status to the friends table
- [ ] An admin should be able to add/edit the ‘eior_case_status’ on the ‘Basic’ tab of the Friend edit page (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_basic_form_fields.html.erb).  This should be a select with the following options: 'Case Pending', 'Immigration Judge Ordered Removal', 'Prior Voluntary Departure', 'Appeal Pending', 'Motion to Reopen Submitted'…plus a blank option.
- [ ] Display the EIOR Case Status on the Friend ‘show’ pages that regular volunteers see (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/f50d36a54e25d1b1601c45f88a37335afa9f49e3/app/views/friends/_info.html.erb)

**Comment by tmaria17** [comment]
I'd like to work on this issue!

**Comment by CZagrobelny** [comment]
Hi @tmaria17 👋 !  Checking in to see if you were currently working on this/have capacity to complete it at this time.  It is fine, if not, it can go back in the pool and there will always be more issues if you have more time to pick up an issue later :)  Thanks!

**Comment by tmaria17** [comment]
Hi @CZagrobelny ! Sorry you can put it back in the pool, I've been really busy with starting a new job but I hope to contribute soon! :)

**Comment by CZagrobelny** [comment]
@tmaria17 of course!  Congrats on the new job! 🎉

**Comment by droza0** [comment]
I'd like to take this on! I just had two questions about tests and docker. Should I make them a separate issue?

**Comment by CZagrobelny** [comment]
@droza0 @ me ('CZagrobelny') on this issue for any questions that are holding you up re: tests and docker.  For suggested improvements to docker or any of the documentation, create a new issue.  I think our docs could be a little clearer here, but Docker is optional and replaces installing Ruby, Rails, and Postgres.

**Comment by droza0** [comment]
@CZagrobelny great, I went ahead and used docker for this feature, wasn't sure if we could just build it using rake db:setup. On tests for this, I was thinking they should go in the feature folder, is that right? And if a new factory is needed (it doesn't look like it is for this particular issue) should we proceed with making it?

**Comment by CZagrobelny** [comment]
@droza0 docker should have run rake db:setup and bundle install: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/docker-compose.yml#L20

When you run 'docker-compose -f docker-compose.yml up' (after building the docker image 'docker-compose -f docker-compose.yml build') you should have the app running at http://localhost:3000 with the seed data
Let me know if you encounter issues with docker.  We added this set up option fairly recently.
  
I think we are ok without tests on this feature.  For the Friend edit flow, we are not testing every field individually (there are a lot of fields).  We do have some feature specs around creating a Friend record and editing a Friend record, but they are selective in what they cover.  Thanks for checking in about the specs, much appreciated!

**Comment by CZagrobelny** [comment]
@droza0 thank you for working on this!  It will help staff determine the risk level of ICE check-ins quickly and is hugely appreciated!
