### ISSUE TITLE
Admins can search for Friends by phone number

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#244]
## Background
NSC Admins want to be able to search for a Friend record by a phone number.

## Implementation
We have a number of filtering options on the Friends index page (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/index.html.erb).  We want to add a text search field for phone # search in a new row above "1 year asylum application deadline ending between dates:"

We are using the filterrific gem for search.  The friend phone number is stored as a string, we don't have any sort of formatting rules on it, since admins frequently add multiple phone numbers and specify if it's, for example, their sister's phone (or some other relation).  So, I think it is best to use the implementation of a search field like 'first name' as a guide.

**Comment by emi1337** [comment]
I'll take this one!

**Comment by CZagrobelny** [comment]
Merged, deployed, notified staff! I've already heard from Melissa about how exciting this is 😀
