### ISSUE TITLE
Volunteers can select the languages they are fluent in

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#245]
## Background
Rather than asking users to identify as 'English Speaker' or 'Spanish interpreter' at account creation, can we ask users to list language(s) in the same way we can list languages for our Friends? (In my ideal world, this means when we see Sherry Kane signed up for an accompaniment next to her name we see "English, French, Spanish") - and could we maybe include "conversational Spanish" as a language option?

## Implementation
- [ ] Associations between Languages and Users should be many_to_many, like we are currently doing for Friends and Languages
- [ ] The user form (for both admins editing users and users editing their own profile) should contain a Language field (multi select).  See here for example: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_basic_form_fields.html.erb#L70
- [ ]  A user accepting an invitation should be able to select their languages (this is a different form than the edit user form).  We use devise invitable for invitations
- [ ] We also need to replace volunteer_type with languages on this user form: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/9019ba4efc091e3b4851751f5604e9ec6877c001/app/views/regional_admin/remote_lawyers/_form.html.erb#L34
- [ ] Replace all instances where we display volunteer_type with the user's languages
- [ ] Remove the 'Volunteer Type' filter on the Users index page (we don't need to replace this with a Language filter at this moment)

Don't worry about a data migration to translate the volunteer role options 'English Speaking' or 'Spanish Speaking' to the Language options.  I can take care of this :)

**Comment by lindsaycooper** [comment]
I'd like to work on this issue

**Comment by CZagrobelny** [comment]
@lindsaycooper sweet, thank you so much!

**Comment by CZagrobelny** [comment]
Hi @lindsaycooper 👋 !  Checking in to see if you were currently working on this/have capacity to complete it at this time. It is fine, if not, it can go back in the pool and there will always be more issues if you have more time to pick up an issue later :) Thanks!

**Comment by lindsaycooper** [comment]
Hi @CZagrobelny. Thanks for checking in. I am swamped at work, catching up from being on vacation so I won't be able to give time to this for at least the next few of weeks. Happy to have it go back in the pool.

**Comment by droza0** [comment]
Hi @CZagrobelny, would like to take this on. Just two questions though:

1. How would I check the devise invitation to see if everything's good? I'd have to receive an invite right? 

2. Are we removing the role field or the volunteer type field on the remote lawyers form?

**Comment by CZagrobelny** [comment]
@droza0 yay!
1.  Yes, this is the view where the user fill in their account info from an invite: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/devise/invitations/edit.html.erb
And to QA, log in as the nyc_admin@example.com user, click on 'Users' in the header, then 'Invite User' button in the upper right.  When you 'invite a user' locally, you'll see the text of the email in your rails s output and can pull the invitation url out of that.
2.  'volunteer_type' sorry about that, have updated in the issue description!

**Comment by droza0** [comment]
@CZagrobelny Great, the invitation has the right field, but for some reason the User's language isn't saving. I can't sort out where users actually get created (no create action in the user's controller), though I guess I'm missing something about how devise works? 

Also, is volunteer type basically deprecated now? So we should remove it as a field as well as where it's displayed?

**Comment by CZagrobelny** [comment]
@droza0 you are right, this coming from a gem 'devise_invitable', I can definitely share some context around what it's doing and how it's configured.
Here is the controller in devise_invitable: https://github.com/scambra/devise_invitable/blob/6825f296ad1da2761976d06b606d15a5dbf0289b/app/controllers/devise/invitations_controller.rb
However, we are overriding the 'create' method here:
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/94cacdd069610b8aa733e92e3d2c2a5f9c17a72c/app/controllers/invitations_controller.rb#L11
And this is where we specified which params are allowed for invited users accepting their invitations: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/94cacdd069610b8aa733e92e3d2c2a5f9c17a72c/app/controllers/invitations_controller.rb#L32
And this is the method in devise_invitable that actually creates a user on invite: https://github.com/scambra/devise_invitable/blob/1d16bee247ccecff195b9d12d9bc374026b82af0/lib/devise_invitable/models.rb#L139

The devise and devise_invitable Readmes are pretty good for a more general picture of how this all fits together.

And re: volunteer_type column.  It is deprecated, but we can leave the column in for now.  For deprecation, I usually separate the work and drop the columns a month or so later.  This makes rollback much less stressful, if needed.  In some cases, the stake holder wants to keep the data.  This probably won't be the case here, but it's a conversation I need to have with them.

**Comment by droza0** [comment]
@CZagrobelny  Got it, thanks so much for the info on how devise works! Next time I'll look more at docs for an issue before asking to take it on! Working on the pull request now.

**Comment by CZagrobelny** [comment]
@droza0 thank you so much for your work on this! Just merged and deployed!
