### ISSUE TITLE
Admins in primary communities see accompaniment attendance represented in a line graph

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#246]
## Background
We would love to show users of the software how much work their community is doing!  We'll start by showing a graph of accompaniment attendance to admins!

## Implementation
ChartKick is a gem to create beautiful js charts with one line of Ruby: https://github.com/ankane/chartkick

This line graph should be titled 'Accompaniments', and should have two lines:
- 'Friends Accompanied' (number of 'confirmed' Activities in the current community with an ActivityType that is 'accompaniment eligible' per week)
- 'Accompaniments' (number of 'Accompaniments' in the current community per week)

This line graph should go on a new page (only visible to community admins) called 'Stats'.  Admins should see a link to this page on the dropdown in the upper right of the navbar header.  It should be the last option (below 'Sanctuaries').  Eventually, we will add more graphs to this page to give admins a sense of how other NSC programs are growing.

**Comment by JShelto** [comment]
Claiming this issue :)

**Comment by CZagrobelny** [comment]
@JShelto and @Keyairra-S-Wright thank you!  We tied up the loose ends and got this merged and deployed, the NSC staff will be very excited to be able to track these metrics week to week! 🙏
