### ISSUE TITLE
Admins can bulk invite users

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#247]
## Background
Following trainings, NSC staff have to copy-paste and submit 150 email addresses individually.  It would be incredible if we could add them all at once!

## Implementation
Rather than making changes to existing invitation functionality, we're thinking a 'bulk invite' feature....something along the lines of:
1.  Admins upload a csv (only need to read one column, just emails)
2.  We validate these emails (use the same criteria devise is using)
3.  We display all of the emails to be invited for the admin to review (maybe this review page indicates which devise has deemed invalid, so they have a heads up)
4.  When they click an 'Invite All' button, we use background jobs to invite all the users.
5.  We redirect them to the Friends index page with a flash message that 'Bulk invitations are going out, refresh in 5 mins to see new users' or something
6.  If an email has been invited in the past hour (User has 'invitation_sent_at'), we do not allow them to be invited via bulk email again (maybe on the 'review' page it could say something about 'just invited -- no email will be sent' for these)

**Comment by nancyhawa** [comment]
I'd like to take this on!

**Comment by CZagrobelny** [comment]
@nancyhawa I'm going to put this one up for grabs, if you circle back to it, just drop me a note and I'll put the 'Assigned' label on it once more!
