### ISSUE TITLE
Admins can see a volunteer's 'Accompaniment History'

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#248]
## Background
Admins would like to be able to see a history of a user's accompaniments!

## Implementation
On the admin user edit page (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/users/edit.html.erb), we want a new header below the 'Has access to Friend records:' header with the text 'Accompaniment History'.

Below this header, we should list every Accompaniment associated with the user in descending user by the 'occur_at' date of the Activity associated with the Accompaniment.  The following information should be listed for the Activity associated with each Accompaniment:

[activity 'occur at' date, should be mm/dd/yy] -- [activity type] for [friend associated with activity as a link to the admin friend edit page]

For example: 01/04/19 -- Check In for Jane Doe ("Jane Doe" links to the admin friend edit page)

Use this as a guide for everything after the '--' : https://github.com/CZagrobelny/new_sanctuary_asylum/blob/90323898b96c66a7175aa191eb1575d184446d6b/app/views/admin/activities/accompaniments.html.erb#L26

**Comment by mgalicer** [comment]
I'll take this on!

**Comment by CZagrobelny** [comment]
Hi @mgalicer 👋 !   Checking in to see if you were currently working on this/have capacity to complete it at this time. It is fine, if not, it can go back in the pool and there will always be more issues if you have more time to pick up an issue later :) Thanks!

**Comment by mgalicer** [comment]
Sorry I won't have time to complete this, you should put it back in the pool! Thanks for checking in :)

**Comment by droza0** [comment]
Would like to take this on as well!

**Comment by droza0** [comment]
@CZagrobelny just wondering about styling convention here. Should I let the history's style (likely without bullets) be a shared ul style, or should ul elements by default not have bullets?

Also, no tests for this one as well? If we should test, do we create a new user_with_accompaniments factory?

**Comment by CZagrobelny** [comment]
@droza0 The bullets looks great!  This one is also ok with no tests.  The only thing I noticed in QA was could we '.titlecase' the activity type name?  Thanks!!!!

**Comment by droza0** [comment]
Titlecased! sorry that took a while!

**Comment by CZagrobelny** [comment]
@droza0 thank you so much!  Merged and deployed! 🙌
