### ISSUE TITLE
Admins can track ankle monitors

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#249]
## Background
When our Friends are monitored electronically with an ankle monitor, we want to track this in the same way that we track Detentions for Friends.

## Experience Level
I've labeled this issue as beginner-friendly because we have an existing similar feature that can provide an example for how to implement the feature.  The scope of these changes is a little larger than I would normally tag as beginner-friendly, so I recommend looking through how the current detention functionality (referenced below) works when evaluating whether to pick up this issue.

## Implementation
- [ ] Database changes: Create a AnkleMonitor table with columns for 'date_applied' (datetime), 'date_removed' (date_time), bi_smart_link (boolean), 'notes' (text), 'friend_id'
- [ ] On the admin edit friend detention tab (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_detention_form_fields.html.erb), add an Ankle Monitor section below 'Detentions'.  **Use the 'Detentions' functionality on this page as a template to build out the following:**
- [ ] an admin should be able to view the Friend's ankle monitoring history
- [ ] and admin can edit an instance of ankle monitoring
- [ ] an admin can add a new ankle monitoring instance for a Friend
- [ ] an admin can delete a Friend's ankle monitoring instance

**Comment by sansbrina** [comment]
👋 I would be happy to pick this up!

**Comment by CZagrobelny** [comment]
That's amazing, thank you @sansbrina!!!

**Comment by CZagrobelny** [comment]
@sansbrina thank you so much for this!  I just merged and deployed the new functionality.
