### ISSUE TITLE
UX Improvements: Regional Admins switching between different communities

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#250]
## Goal
1.  Make it clear to the Regional Admin which community they are currently viewing
2.  Make switching between communities a little easier
Video with more context is here:  https://drive.google.com/open?id=1wM-RVYT14X9Z-xoMNyvi5GI-hOvAWFpY

## Implementation
- [ ] Add the community name into the top header after New Sanctuary Coalition to make the community clearer
- [ ] Add a nested drop down to include all the communities in each region in the Regional Management dropdown.  These can just be links to the '/communities/[COMMUNITY_SLUG]/admin' path for each community.  The functionality to edit a community or add a new community for the region can stay where it is (with the same link in the dropdown, '[Region Name] Communities')...which the communities are now nested under.
- [ ] Open to additional recommendations if you have any, can chat in the comments!

**Comment by sansbrina** [comment]
A couple initial thoughts:
1. Perhaps adding the community name into the top header after `New Sanctuary Coation` would help make the current community clearer?
2. A nested drop down would save clicks when switching but I'm not sure how nicely it would scale/how necessary the options in the table (community slug with the edit button) are to access or where they would go instead.

Just wanted to put some thoughts out there in hopes of starting a conversation & seeing what's been considered already. I'm not a UX expert by any means.

**Comment by CZagrobelny** [comment]
@sansbrina these are great suggestions!  Thank you for sharing them!  And they would certainly work well for the regions and communities we have so far.

**Comment by CZagrobelny** [comment]
Merged! 🙌
