### ISSUE TITLE
#update tests not working as expected

### ISSUE THREAD

**Issue by nancyhawa** [CZagrobelny/new_sanctuary_asylum#255]
I think it may be that the controller tests for #update methods aren't working as expected.  For example, in [spec/controllers/admin_access/users_controller_spec.rb ](https://github.com/CZagrobelny/new_sanctuary_asylum/blob/5811997252d9fba38d0c14cccc0806cc4d6197ae/spec/controllers/admin_access/users_controller_spec.rb#L29) we've got this test:
```
describe 'PUT #update' do
      let!(:user) { create :user, community: community }
      it 'allows access' do
        user.first_name = 'new name'
        put :update, params: { community_slug: community.slug, id: user.id, user: user.attributes }
        expect(user.first_name).to eq 'new name'
      end
    end
```

This creates the user, then sets the users first name to 'new name', then completes the `PUT` and checks that the first name was changed.  However, if I delete [line 81](https://github.com/CZagrobelny/new_sanctuary_asylum/blob/5811997252d9fba38d0c14cccc0806cc4d6197ae/app/controllers/admin/users_controller.rb#L80) of the `Admin::UsersController` which removes first_name as a permitted parameter, I can confirm in the interface that admins an no longer change the first name of a user, but the tests still pass.

My hypothesis is that the test is roughly equivalent to the test below and the `PUT` doesn't do anything.

```
    it 'allows access' do
        user.first_name = 'new name'
        expect(user.first_name).to eq 'new name'
      end
```

I discovered this trying to write tests for Issue #239 but wanted to run it by @CZagrobelny to see if you've got another take.  That was a unique case, because I wanted to confirm that an attribute DID NOT get changed in a specific circumstance, so the testing behavior became more clear. If you agree, you can assign this issue to me and I'll update existing tests.

**Comment by CZagrobelny** [comment]
@nancyhawa I'm going to put this one up for grabs, if you circle back to it, just drop me a note and I'll put the 'Assigned' label on it once more!

**Comment by CZagrobelny** [comment]
Completed!
