### ISSUE TITLE
Admins can search for a Friend by matches in the 'notes' field

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#258]
## Background
NSC Admins want to be able to search for a Friend record by matches in the 'notes' field.

## Implementation
We have a number of filtering options on the Friends index page (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/index.html.erb).  We want to add a text search field for phone # search in a new row above "1 year asylum application deadline ending between dates:"

We are using the filterrific gem for search.  The friend 'notes' is stored as a text.   The implementation of a search field like 'first name' should be a pretty good guide.

**Comment by emi1337** [comment]
I can take this one too :)

**Comment by CZagrobelny** [comment]
Merged! 🙌 🙏
