### ISSUE TITLE
Add social work referrals to Friend records

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#266]
## Background
During the pro se legal clinic, social work interns are available to meet with Friends and may provide referrals to services for shelter, mental health, ESL, and food assistance.

## Experience Level
I've labeled this issue as beginner-friendly because we have an existing similar feature that can provide an example for how to implement the feature.

## Implementation
Admins would like to track the categories of services a Friend has been referred to on their Friend record.  A community admin editing a Friend record on the 'Other Case Info' tab should see a new section 'Social Work Referrals' above the 'Lawyer' section.

This section should have:
- [ ] a 'Social Work Referral' field that is a multi-select (for multiselect, make use of chosen js, see the 'Languages' field on the Basic tab of a Friend record as an example of how chosen js works)
- [ ] a 'Social Work Referral Notes' text field

Database changes:
- [ ] Add a social_work_referral_categories table with a name column
- [ ] Add a join table between friends and social_work_referral_categories
- [ ] Add a social_work_referral_notes column to the friends table

We don't need to add information about social work referrals to any interfaces that non-admin users see.

The implementation of adding Languages for Friends is a good model for the behavior, associations, and data model we want, use this as a reference!

- [ ] Create seed data to populate the social_work_referral_categories table.
Here is an example for a similar task for languages: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/lib/tasks/populate_languages.rake
It should be invoked like we are doing here: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/db/seeds.rb#L9

The categories should be (displayed in alphabetical order):
- Shelter/housing
- Health Care Services
- Mental Health Services
- Advocacy Services
- Psychiatric Evaluation for Immigration Case
- ESL
- Nutrition Services
- Public Benefits
- IDNYC

**Comment by carodelafuente** [comment]
Claiming this one with @ombene

**Comment by CZagrobelny** [comment]
Merged and deployed!  @carodelafuente and @ombene, thank you so much for your work on this! 🙌
