### ISSUE TITLE
Admins can see who last edited activities

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#271]
## Background
Knowing who last edited an Activity would be really helpful to admins as they are preparing the activities for the week.  We are now accompanying Friends to 50-70 activities per week!

## Implementation

Database Changes:
- [ ] add a last_edited_by column to the activities table

When an activity is created/updated, the id of the logged-in user should be set as last_edited_by. There are several places where we create/update activities:
- [ ] https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/controllers/accompaniment_leader/friends/activities_controller.rb#L6
- [ ] https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/controllers/admin/activities_controller.rb
- [ ] https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/controllers/admin/friends/activities_controller.rb

'Last edited by: [user name]' should be displayed in this partial for admins to see.  You should see this appear for activities on the Friend edit (Activities/Accompaniments tab) AND for the modals on the Activities calendar and the Accompaniment calendar.  Partial:
- [ ] https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/activities/_activity.html.erb#L18

**Comment by parkjimin0** [comment]
Jenina and I will pick this one up :)

**Comment by jcgrayson** [comment]
Picking this one up with @parkjimin0

**Comment by carodelafuente** [comment]
Working with @jcgrayson and @parkjimin0 on this.

**Comment by CZagrobelny** [comment]
@jcgrayson , @carodelafuente, and @parkjimin0 merged and deployed!  Thank you so much for your work on this, the staff will be very, very excited to have the ability to keep track of this! 🙏
