### ISSUE TITLE
Allow admins to add individual notes to a Friend record

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#273]
## Background
The 'Notes' field on Friend has proven to be one of the most invaluable fields on the Friend record!  It often includes information that shows the history of a Friend's case, and when admins add onto the notes (it's a single field at this point), they date and initial their additions.  It would be EVEN better if this could be done automatically when individual notes are added.

## Implementation

Database Changes:
- [x] add a new table 'friend_notes' with columns 'friend_id', 'last_edited_by' (this will be a user id), 'note' (text), and timestamps

I think what we want for the model is for a friend_note to belong_to both Friend and User.  And User and Friend have many friend_notes.  Also, I think we want to restrict destroying a user record if it has friend_notes (we can do this in associations with dependent: :restrict_with_error)

When an admin is editing a Friend record, on the 'Basic' tab, where they currently see the notes field (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_basic_form_fields.html.erb#L136), they should instead see:
- [x] a notes header
- [x] a list of the Friend's notes that includes the text of the note, the name of the user who last edited it, and the date it was last edited

And, they should be able to:
- [x] create a note for a Friend
- [x] edit any of the Friend's notes
- [x] delete a note for a Friend

We have a pattern for creating/updating/deleting associated records within the Friend form.  Check out adding 'detentions' on the detention tab for an example (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/detentions/_list.html.erb).  I expect this could be implemented pretty much the same.

Also, we can remove Friend notes entirely for volunteers (they don't need to see it): https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/friends/_info.html.erb#L20

You don't need to worry about writing migrations or tasks to copy over the existing data on the Friend note field, I'll take care of that :)

**Comment by halfghaninne** [comment]
I'm interested in this issue!

**Comment by CZagrobelny** [comment]
Merged and deployed! 🙌
