### ISSUE TITLE
Allow admins of non-primary communities to manage Lawyers for the region

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#278]
## Implementation
Right now, only admins of primary communities can manage Lawyers for the region.  We want admins of non-primary communities to be able to manage Lawyers for the region as well.  This should just be a matter of adjusting permissions and conditional logic.

**Comment by mrz1988** [comment]
If I understand this correctly, this is managing `remote_clinic_lawyer` _user_ instances for the region?

**Comment by CZagrobelny** [comment]
@mrz1988 it is different.  Sorry lawyer is one of the very confusing things.  This is the lawyers table.  I'm going to reach out in slack
