### ISSUE TITLE
An admin can 'hide' Judges from the list

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#280]
## Background
Over the years, admins have added a lot of Judges to the software (these are associated with activities that are immigration court hearings).  There are a number of these judges that are no longer presiding in immigration court in NYC, so it would be helpful for admins to be able to 'hide' these judges from appearing in the judges index and judges dropdown menus.  We don't want to completely delete these judges because that would remove them from our records of past activities (court dates)

## Implementation
- [ ] add a `hidden` boolean column to the `judges` table
- [ ] the admin judges index page should contain links to `hide` (ie. update `hidden` to `true`) for each of the judges (this can be a new column on the right of the table). 
- [ ] all dropdown menus that list judges should only contain judges where `hidden` is NOT `true`

**Comment by patcoll** [comment]
👋 I've started to work on this

**Comment by CZagrobelny** [comment]
@patcoll thank you for this PR!  I'll have a chance to review this weekend!
