### ISSUE TITLE
An admin can track and filter for activities that have a TBD date

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#281]
## Background
Increasingly our Friends are being given TBD dates or a 'control date' for their next hearing.  This puts our Friends at great risk of missing a hearing if they don't receive notification in time.  We have had numerous close calls where our Friends get notified of their new hearing date only a day before their hearing or we only catch that they have been assigned a date by calling the EIOR hotline for all Friends who have been given these TBD hearings every week.  It is getting unmanageable and we need to put a system in place to record this data and then reliably search for everyone awaiting a date, which will allow our volunteers to call EIOR for each of our Friends and check to see if they have been assigned a date.  A 'control date' is the date by which EIOR will set the actual date for a hearing.  It does not mean that the hearing will occur after the control date, sometimes it will be scheduled before the control date, so both 'TBD' and 'control date' hearings need to be checked on frequently.    

## Implementation
- [ ] add the following columns to `activities`: `occur_at_tbd` (boolean), `control_date` (datetime)
- [ ] change Activity validations to require that an activity has a value for `occur_at` OR `occur_at_tbd` is true OR `control_date` has a value.
- [ ] add 'Date TBD' and 'Control Date' checkboxes and 'Control Date' datepicker (they can all go below the `occur_at` field) to the activity forms.  
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/3062764dca5c712cb9596e980648b3b02717fbeb/app/views/admin/friends/activities/_form.html.erb
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/cc2d0c5f1b9f8b9819969ab60b59371cbe806617/app/views/accompaniment_leader/friends/activities/_form.html.erb
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/3062764dca5c712cb9596e980648b3b02717fbeb/app/views/admin/activities/_form.html.erb
We can use a jQuery calendar datepicker on the 'Control Date' field because these dates are likely to be in the next couple months.
- [ ] there are a bunch of places where we were banking on `occur_at` being a required attribute. Starting with a search for 'activity.occur_at', make appropriate changes so that an activity without an `occur_at` value does not raise an error.  Several of these places are dealing with a data set that has an occur_at date because they are being displayed on a calendar, so those should not be an issue.
- [ ] IF an activity is 'Date TBD', display this on the activity information.  IF an activity is 'Control Date', display this and the `control_date` datetime on the activity.
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/3062764dca5c712cb9596e980648b3b02717fbeb/app/views/admin/friends/activities/_list.html.erb
- [ ] A community admin on the admin friends index, should be able to filter for ALL Friends that have an activity where `occur_at_tbd` is true OR `control_date` is true.  This can be a single checkbox for both called 'TBD or Control Date Activity'.  We use the filterrific gem for filtering. https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_search_friends.html.erb

**Comment by RajdeepRao** [comment]
Hey @CZagrobelny planning on working on this one if that's okay?

**Comment by CZagrobelny** [comment]
@RajdeepRao and @jnhooper merged and deployed!  Thank you SO MUCH for all of your work on this feature! 🙏
