### ISSUE TITLE
difficulty getting docker running from a fresh pull

### ISSUE THREAD

**Issue by jnhooper** [CZagrobelny/new_sanctuary_asylum#282]
When I pull down the repo and try to get up and running using docker for the first time I run into this error

<img width="912" alt="image" src="https://user-images.githubusercontent.com/8321632/68624283-7ad2bb80-04a4-11ea-9ccb-2649e8cb528a.png">

I believe this is an issue with not having access to the .ruby-version before running the bundler

**Comment by jnhooper** [comment]
I think I have a quick fix for this, I'll fork and open a PR

**Comment by CZagrobelny** [comment]
@jnhooper thanks so much!  This was a recent change to try to make it easier to keep the ruby version in sync, thank you for catching this issue with the docker set up!

**Comment by jnhooper** [comment]
https://github.com/CZagrobelny/new_sanctuary_asylum/pull/283
here is a link to the PR, pretty small and its possible there's a `cooler` docker solution but this should fix the issue for the time being i think

**Comment by jnhooper** [comment]
closing because it got merged in
