### ISSUE TITLE
Track judge-imposed asylum application deadlines

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#302]
## Background
ICE has been fast-tracking deportations for families who cannot prove that they have lived in the US for more than a year.  They do this through the 'Family Unit Docket', which is a fast-track docket for deportation proceedings.  Ordinarily, asylum seekers have 1 year from when they enter the country to file an asylum application.  Judges in the 'Family Unit Docket' have started imposing their own deadlines  (well before the 1-year deadline) for families on their docket to file asylum applications.  This affords families (and NSC) significantly less time to put together an asylum application and try to find a lawyer to represent them in court for arguments on their asylum application.  NSC staff needs a system to track these deadlines as soon as the judge orders them because every day counts.

## Implementation
- [ ] Add a column to the `friends` table: `judge_imposed_i589_deadline` (datetime)
- [ ] This will require some refactors to the way that we are currently collecting 'accompaniment_reports'  from accompaniment leaders after the accompaniment.  Rather than a form for the `accompaniment_report`, we now want a form that contains both the NEW `accompaniment_report` and our new `judge_imposed_i589_deadline` attribute on `friends`.  I think this is a good use case for Rails Nested Attributes (https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html).  We would first need to add an association (an `accompaniment_report` belongs_to a `friend`).  And then we could refactor the existing `accompaniment_report` CRUD functionality to be nested in a `friend` form.  The form should include nested attributes for accompaniment_reports (keeping the current behavior in which an accompaniment leader can only create one accompaniment report AND can only edit an accompaniment report that they have authored).  The friend form should contain the field 'Judge-imposed i589 Deadline'.  It should be a date selector (we can use the jquery datepicker https://jqueryui.com/datepicker/...we're already using it in a few places).
- [ ] We should add this field to the Friend edit form for admins: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_basic_form_fields.html.erb#L135
- [ ] Add a search filter to allow admins to filter all Friends with a `judge_imposed_i589_deadline` that falls within a date range, similar to the filter we have for the regular 1-year i589 deadline: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_search_friends.html.erb#L59  (the `judge_imposed_i589_deadline` filter can go just below this one).  We use the filterrific gem for search and you should largely be able to copy the implementation of the regular 1-year i589 deadline filter.

**Comment by lavaturtle** [comment]
I can do this one!

**Comment by CZagrobelny** [comment]
Thanks @lavaturtle !!! Marking it assigned!

**Comment by CZagrobelny** [comment]
@lavaturtle merged and deployed!  Thank you so much for taking this on (including the refactor), this will make it so much easier to track the deadlines that are issued.
