### ISSUE TITLE
Add 'No Record in EOIR' and 'Order of Supervision' to Friend records

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#303]
## Background
Some of our Friends are in removal proceedings, but have not yet been added to EOIR's system ('Executive Office for Immigration Review').  Our Friends are not notified when they are added to EOIR, but once they are added, NSC can get their next hearing date by calling the EOIR hotline.  This is important because hearings get scheduled with very little notice, which puts our Friends at risk of inadvertently missing a hearing.  NSC staff want to be able to flag Friends who have not been added to EOIR's system and to search for these Friends.

Some of our Friends are given an 'Order of Supervision', which for us means: the risk of them being detained and possibly deported is higher than for the rest of our Friends.  It's important that we have this information on hand for the Accompaniment program.  And we want to be able to search for Friends that have an 'Order of Supervision'.

## Implementation
- [ ] add a column `no_record_in_eoir` to the `friends` table
- [ ] add a column `order_of_supervision` to the `friends` table
- [ ] add checkboxes for 'No Record in EOIR' and 'Has Order of Supervision' on the Admin Friend form: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_basic_form_fields.html.erb#L128
- [ ] Add a filters for the new columns on the Friend search view. 
 We can add them here with the other checkboxes: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_search_friends.html.erb#L29.  I believe if we shorten the labels to 'Not in EOIR' and 'OSUP', they should both be able to fit on the same line as the other checkbox filters.  🤞 'OSUP' is an abbreviation the staff has been using for 'Order of Supervision'.  We are using the filterrific gem for filtering, and you should be able to use the other checkboxes as an example implementation.

**Comment by joshco** [comment]
Still have work to do, but the filter checkboxes fit:
![image](https://user-images.githubusercontent.com/290314/72673683-ac7f7a00-3a33-11ea-8050-66c2bd31baac.png)

**Comment by joshco** [comment]
WIP:  Would prefer review before I create the PR (dont merge yet)
I think I've done the parts needed.  Can you take a look?
In the migration, I made the booleans have default false.

**Comment by CZagrobelny** [comment]
@joshco I took a look at the branch, it is the changeset I was expecting and looks great!  Thank you for making the booleans default to false, it's something that hasn't been done consistently in this codebase over the past few years, but it's definitely the right call.

**Comment by CZagrobelny** [comment]
Merged and deployed!
