### ISSUE TITLE
Accompaniment Leaders can indicate if a Friend has a lawyer in their accompaniment report

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#305]
## Background
When accompaniment leaders file their 'report' following an accompaniment, it would be amazing if leaders could indicate whether the Friend has a lawyer. This could be an optional checkbox for "has a lawyer" followed by optional text box for lawyer name and contact info.  This would help us cut down on guesswork and lots of phone calls to folks with upcoming individual hearings (hearings where a judge will decide a Friend's immigration case) to ask whether they have an attorney and invite them back to clinic. If we collected this info another way, it would save us some time and save our Friends from one stressful conversation.

## Implementation
**FYI: You may notice that there is a `lawyers` table and a couple columns on the `friends` table that indicate the id of the lawyer a friend was referred to or is represented by.  We won't be using the `lawyers` table or these columns for this feature.   I am hoping/suspect that what we will implement with this issue will ultimately replace our current Lawyer functionality.**

- [ ] add a column `has_a_lawyer` (boolean) to `friends` table
- [ ] add a column `lawyer_name` (text) to `friends` table
- [ ] when an accompaniment leader creates an accompaniment report, they should also be able to edit the 'Has a Lawyer' checkbox and the 'Lawyer Info' field for the Friend (we are currently using nested attributes to include fields on the Friend model: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/accompaniment_leader/accompaniment_reports/_form.html.erb#L17)
- [ ] add these two fields to the admin friend edit form, 'Other Case Info' tab (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_other_case_info_form_fields.html.erb)
- [ ] add a search filter (checkbox) for the `has_a_lawyer` field.  This is on admin friends index. (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_search_friends.html.erb)

**Comment by lavaturtle** [comment]
I'd like to take this on!

**Comment by CZagrobelny** [comment]
@lavaturtle yay!  Thank you!!!!!

**Comment by CZagrobelny** [comment]
Merged!  Thanks so much @lavaturtle !!!!
