### ISSUE TITLE
Admins can indicate what a Friend is planning to work on at clinic

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#308]
## Background
In our pro se legal clinic, we schedule Friends to come to clinic using the ‘cohort’ functionality. It would be really helpful if NSC staff could also indicate what the Friend was coming to clinic to work on.

## Implementation
- [ ] add a `clinic_plan` (string) column to `friends` table
- [ ] Admin should a dropdown in the ‘Clinic’ tab of admin friend edit, under the Cohorts header (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_clinic_form_fields.html.erb#L41) that contains the following options, displayed in titlecase: ‘i589’, ‘individual_hearing’, ‘motion_to_reopen’, ‘appeal’, ‘osup_rfi’, ‘consultation’, ‘foia’, ‘change_of_venue’, ‘work_permit’ (follow implementation example of ‘STATUSES’ in Friend.rb
- [ ] Display the Friend’s clinic_plan (titlecases) in a new column in the table on admin cohort show (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/cohorts/_friend_assignment.html.erb#L6)

**Comment by lavaturtle** [comment]
I'll do this one.

**Comment by CZagrobelny** [comment]
Merged and deployed!  Thank you so much @lavaturtle, the staff will be so happy to have this feature to help organize clinic!!!
