### ISSUE TITLE
Admins can filter for Friends who have an Activity with a specific Location or Judge

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#310]
## Background
Being able to search for Friends who have a an Activity with a specific ActivityType that occurs in a specific date range has been really helpful.  Building on that functionality, staff would like to be able to filter for all Friends who have an Activity with a specific Judge and/or at a specific Location.  This will help NSC staff track trends around case outcomes.  One request that has come up recently is that NSC staff have noticed specific judges and specific locations ordering electronic monitoring (ankle monitors) on our Friends at a high frequency, and they want to pull together a report on this.

## Implementation
We want two new search filters on admin Friend search:
- 'with Judge', should be a searchable dropdown multiselect using chosen js that has all of the Judge names (scope: Friend has an Activity with any of the selected judge ids) 
- 'at Location', should be a searchable dropdown multiselect using chosen js that has all of the Location names (scope: Friend has an Activity with any of the selected location ids)

Use the ActivityType filter dropdown as an example for implementation: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_search_friends.html.erb#L60

With the addition of these dropdowns, the activity search filters on Friend will now span multiple lines.  It would be helpful if maybe there was a dividing section line above and below.  Within the activity search filters section, I'm thinking it could be laid out like:
"Has activity [ActivityType dropdown] between [Activity StartDate datepicker] and [Activity EndDate datepicker] with [Activity Judge dropdown] at [Activity Location dropdown]"

Also, the way we are currently controlling the width of the other chosen searchable dropdowns on Friend search is pretty hacky:
https://github.com/CZagrobelny/new_sanctuary_asylum/blob/9cb7251347f066630900d509df0cd7e90e492738/app/assets/javascripts/admin_friend_form.js#L61
Would love to make this better, now that we're adding two new searchable multiselect dropdowns on Friend search.

**Comment by emi1337** [comment]
i can do this!
