### ISSUE TITLE
Remove Review Emails Sent to Regional Admins

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#315]
## Background
The 'review' emails for remote clinic that are sent to regional admins are not very helpful and we want to remove them.

## Implementation
The emails we want to no longer send are:
- [ ] Review needed: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/da7152d140730100549ea6bd9b75ead95af2ddeb/app/mailers/review_mailer.rb#L4 
- [ ]  Lawyer assignment needed: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/mailers/review_mailer.rb#L11

If you're unfamilar with Rails Action Mailer, here's some documentation about them for more context on the pieces of the mailer functionality for these two methods that need to be removed: https://guides.rubyonrails.org/action_mailer_basics.html

**Comment by boom100100** [comment]
I can do this one.

**Comment by boom100100** [comment]
This is just for the methods, right? I shouldn't do any changes to related layout files and tests?

**Comment by CZagrobelny** [comment]
@boom100100 yes, we should also remove the tests for these methods and the view files (which can be found in here: https://github.com/CZagrobelny/new_sanctuary_asylum/tree/master/app/views/review_mailer)  Let me know if you have any other questions.  Thanks!

**Comment by CZagrobelny** [comment]
@boom100100 merged!  Thanks so much for helping out with this!!!
