### ISSUE TITLE
Highlight high-risk ICE check-ins with color coding

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#316]
## Background
NSC is now accompanying ~60 people each week in NYC.  When admins look at the accompaniment calendar, they want a visual cue to pick out the high-risk ICE check-ins.

## Implementation
Similar to the way we are making activities for Friends who are in detention display in red on the calendar (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/activities/accompaniments.html.erb#L17), we want to have Activities with an ActivityType with `name`='high_risk_ice_check_in' display in *purple* on the calendar.  ActivityTypes (table: `activity_types`) are stored in the database and the seed data does not have an ActivityType with the name 'high_risk_ice_check_in', so you'll have to create this ActivityType in your local database in order to make sure it's working.

**Comment by emi1337** [comment]
I can take this tonight!

**Comment by CZagrobelny** [comment]
Wound up not picking this one up because we were focused on planning to run the pro se clinic remotely, so it's currently available.

**Comment by rsl** [comment]
- add legend for colors
- update seed data to use names that follow current `ruby_case` convention 
-  refactor https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/activities/accompaniments.html.erb#L17 to use `content_tag`  and a helper for class instead of inlining conditional inside attribute assignment

**Comment by rsl** [comment]
can you get me some sample activity types?

**Comment by CZagrobelny** [comment]
special_accompaniment
check_in
high_risk_ice_check_in
criminal_court
bond_hearing
fingerprinting
filing_asylum_application
asylum_granted
filing_work_permit
detained
guardianship_requested
sijs_special_findings_form_finished
sijs_application_submitted
sijs_granted
sijs_denied
change_of_venue_submitted
foia_request_submitted
foia_recieved
I_130_sent
stay_of_deportation_filed
u_visa_filed
habeas_corpus_filed
family_court
appeal_deadline
letters_of_support_deadline
motion_to_reopen
biometric_appointment
asylum_interview
filing_motion_to_reopen
filing_motion_to_appeal
bond_granted
bond_denied
master_calendar_hearing
individual_hearing
out_of_region_hearing
out_of_region_check_in
eoir_ordered_removed
eoir_appeal_received
eoir_appeal_denied
eoir_motion_to_reopen_received
eoir_motion_to_reopen_denied
