### ISSUE TITLE
UX Improvements: Remote Clinic Lawyer View

### ISSUE THREAD

**Issue by emi1337** [CZagrobelny/new_sanctuary_asylum#327]
Right now the Remote Clinic Lawyer view is pretty much the same as the Regional Admin's view, but their needs are very different. Remote Lawyers sometimes need to be onboarded quickly or last minute and are really important, so we need this experience to be improved and with more education provided to help lawyers know where to take action.

**Comment by CZagrobelny** [comment]
Merged! 🙌
