### ISSUE TITLE
UX Improvements: Regional Admin Table View

### ISSUE THREAD

**Issue by emi1337** [CZagrobelny/new_sanctuary_asylum#331]
Regional Admins might have pretty similar needs as the remote lawyers, so they could likely share some of the UI that was built for them. See issue: https://github.com/CZagrobelny/new_sanctuary_asylum/issues/327

If not sharing code, we could base designs roughly off of it:
<img width="1503" alt="Screenshot 2020-04-20 21 46 03" src="https://user-images.githubusercontent.com/1188988/79817981-ac558a00-8354-11ea-9575-a385bb1ffc00.png">

**Comment by emi1337** [comment]
working on this now~

**Comment by CZagrobelny** [comment]
Thank you!  This looks awesome, merged!  🙌
