### ISSUE TITLE
account lock down

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#365]
# Description
We would like a user to be able to 'lock down' their account without being authenticated.
At the path '/lockdown', there should be a form with an email field input and a submit button.
When this form is submitted, we should locate the user (trim whitespace and make sure the search is not case sensitive).  Then we should set a new, very strong password for the user in devise:
```
password = SecureRandom.uuid + SecureRandom.uuid.upcase
user.reset_password(password, password)
```
The user should then be redirected back to the form page '/lockdown'.  We can display a flash message to indicate whether or not this was successful.
Resetting the password will log out the user wherever they are logged in and will require the user to go through 2FA the next time they log in.

**Comment by boom100100** [comment]
@CZagrobelny What's the ideal controller / view pattern? I'm trying to figure out where to put this.

**Comment by CZagrobelny** [comment]
@boom100100 good question, I'm thinking make a 'lockdown_controller' and in that controller we can have a 'new' action (the form page) and a 'create' action (posting the form).  This will allow you to use Rails resourceful routing (https://guides.rubyonrails.org/routing.html#resource-routing-the-rails-default).  The 'new' view file can go in a folder named 'lockdown', corresponding with the controller name and the routing.

**Comment by boom100100** [comment]
@CZagrobelny I'm having some trouble pushing my changes. Can I get access to push to a sub-branch?

`git push --set-upstream origin account_lock_down
remote: Permission to CZagrobelny/new_sanctuary_asylum.git denied to boom100100.
`

**Comment by CZagrobelny** [comment]
@boom100100 you should be able to make a PR by forking the repo, this guide walks through the process of forking the repo and making a PR on the main project: https://guides.github.com/activities/forking/

**Comment by CZagrobelny** [comment]
Merged!  Thank you so much for your work on this @boom100100 !
