### ISSUE TITLE
Improve Access Time Slot record keeping

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#372]
## Background
Currently, 'access time slots' can be edited and deleted by admins at any time.  We want to add some restrictions to make sure we have an accurate history while still allowing editing and deletion in some circumstances.

## Implementation
- If the time is *before* the start of an access time slot, an admin may edit or delete the access time slot.
- If the time is *after* the start of an access time slot, admins should no longer be permitted to edit the access time slot.
- If the time is *after* the start of an access time slot and *before* the end of the access time slot, an admin should be able to deactivate (rather than delete) the access time slot.  When an access time slot is deactivated, it should not grant the logged-in user admin access.  There should also be some visual indication on the access time slot calendar that the access time slot has been deactivated.
- If the time is *after* the end of an access time slot, an admin should not be able to edit, delete, or deactivate an access time slot.

**Comment by lavaturtle** [comment]
I'd like to work on this one!

**Comment by CZagrobelny** [comment]
@lavaturtle yay, thank you!!!!  Marking it assigned, and please let me know if you have any questions.  Thanks!

**Comment by CZagrobelny** [comment]
Merged and deployed!  🚀 Thank you so much, @lavaturtle!!!
