### ISSUE TITLE
Color Code Stages of Review

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#75]
Draft is Blue
Submitted for Review is Orange
Changes Requested is Deep Red
Approved is Green

**Comment by PBeier** [comment]
I would like to work on it!

**Comment by CZagrobelny** [comment]
@PBeier the prerequisite work for this is actually in a forked repo.  Long story short, we recently participated in a hack event called Ruby For Good.  This issue will help us finish up the work we started there and get the master branch of the fork merged back into the main repo.

This issue wound up in the wrong repo, but I added it to the other repo with much more context.  Since this is tagged as beginner the description is a little heavy on implementation details, just as a heads up.

So, you can check out the issue here:  https://github.com/rubyforgood/new_sanctuary_asylum/issues/14

Clone the repo that this issue lives in and create a branch off master for the work.  When you create a PR, you'll have to specify that you want to compare against the forked (rubyforgood) repo.

Let me know if you have any questions!  Just added you as a collaborator on the other repo.
