### ISSUE TITLE
Add specs for a lawyer/regional admin approving a draft

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#89]
Happy path feature spec:
When a lawyer or regional admin 'approves' a draft (click the approve button next to a draft and confirms in the js confirm)
- the draft status is :approved
- the draft's application status is :approved
- 'application_approved' email is sent
- the lawyer or regional admin sees a success message
- the lawyer or regional admin is redirected to the correct path

**Comment by enyuhsu** [comment]
I'll take this one!
