### ISSUE TITLE
Feature:  Family court hearings are capped at 3 volunteers

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#91]
Context: when we accompany our friends to Family Court, we need to cap volunteer attendance at 3 people. Note, accompaniment leaders who are attending should not count to the 3 volunteer limit.

Implementation:
'family_court' is a type of activity, and it is eligible for accompaniments. We should add a validation on the Accompaniment model to make sure that we don't create more than 3 accompaniments (where the user is a volunteer) per family_court activity. If a user attempts to RSVP, they should see an error message. We should also have conditional logic to hide the RSVP button on the volunteer accompaniments page ('/activities') from volunteers not currently attending a family court activity that has reached it's volunteer cap. Volunteers who are attending a family court activity should still see the 'Edit RSVP' button.
Volunteers ('/activities') and accompaniment leaders ('/accompaniment_leader/activities') viewing upcoming activities should see the text in italics '3 volunteers needed.' below family_court activities.

**Comment by latazzajones** [comment]
@CZagrobelny I can pick this up if no one is working on it.

**Comment by CZagrobelny** [comment]
@latazzajones that would be great!  Also as a heads up, in the next week or so, I'll be moving this repo to an organization account.

**Comment by latazzajones** [comment]
To Do: 
- [ ] validate only 3 accompaniments per family_court activity
- [ ] Add error message if user attempts to RSVP when there are already 3 accompaniments
- [ ] Hide the RSVP button on the volunteer accompaniments page ('/activities') if the viewer is not already attending and the limit is reached
- [ ] Volunteers already attending should see an 'Edit RSVP'
- [ ] Volunteers ('/activities') and accompaniment leaders ('/accompaniment_leader/activities') viewing upcoming activities should see the text in italics '3 volunteers needed.' below family_court activities.

**Comment by CZagrobelny** [comment]
@latazzajones merged! Thank you!!!
