### ISSUE TITLE
Feature: Require a js confirm for Community Admins deleting an Activity

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#92]
Community admins should see a JS confirm modal asking if they are sure they want to delete when they attempt to delete an activity.
This is the view where admins delete an activity:  https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/activities/_activity.html.erb#L32

**Comment by hwigmore** [comment]
@hwigmore

**Comment by CZagrobelny** [comment]
Merged!  Thank you @hwigmore !
