### ISSUE TITLE
Feature: Display a person icon on activity details in the Accompaniments calendar

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#94]
Context:  This is for the calendar that admins look at to see scheduled accompaniments.  Each accompaniment needs to have an accompaniment_leader attending, so it would be helpful for admins to see which accompaniments have leaders and which do not at a glance.

Request:  To the right of the check mark icon which is conditionally displayed on the Accompaniments calendar, ADD a person icon that will be displayed IF the activity has one or more accompaniment leader attending.

Implementation Details:

Accompaniment calendar:  https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/activities/accompaniments.html.erb#L8

We are using font awesome in the app, let's use the following for the person icon: <i class='fa fa-user'></i>

In activity.rb, we have the following method to return accompaniments for an activity by a user with the 'accompaniment_leader' role: accompaniment_leader_accompaniments

**Comment by chenyejia** [comment]
Hi, can you assign me to this issue? :)
