### ISSUE TITLE
Feature:  Add the number of accompaniment volunteers to the activity display on the Accompaniment calendar

### ISSUE THREAD

**Issue by CZagrobelny** [CZagrobelny/new_sanctuary_asylum#95]
Context: This is for the calendar that admins look at to see scheduled accompaniments. Admins need to make sure that we have enough volunteers signed up for each accompaniment, so it would be helpful for admins to see the number of volunteers signed up for each activity at a glance.

Request:  Immediately after the link that includes the type of activity and name of the friend, ADD the number of volunteers attending the activity.  Should be in parenthesis, just the number, for example (12). This should not be part of the link.

Implementation Details:

Accompaniment calendar: https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/activities/accompaniments.html.erb

This count should just include the users with the role 'volunteer' who are attending and should not include users with the role 'accompaniment_leader' who are attending.
In activity.rb, we have the following method to return accompaniments for an activity by a user with the 'volunteer' role: volunteer_accompaniments

**Comment by acatxnamedvirtue** [comment]
I'll grab this one :)

**Comment by acatxnamedvirtue** [comment]
Opened PR #103 for this

**Comment by CZagrobelny** [comment]
@acatxnamedvirtue, your PR looks great, thank you!!!
