### ISSUE TITLE
Clarify nesting of Postgres instructions

### ISSUE THREAD

**Issue by lisavogtsf** [CZagrobelny/new_sanctuary_asylum#96]
At WSC2018 I got confused about which postgres instructions applied to me or not. I suggest someone look closer and provide a cleaner way to understand those instructions.

If I want to use the Postgres.app, how do I create my user? Should I just use psql instead? etc.

**Comment by CZagrobelny** [comment]
@lisavogtsf made some changes to the postgres instructions, thanks for adding this!
