### ISSUE TITLE
Activity not showing up after initial failed save attempt

### ISSUE THREAD

**Issue by hwigmore** [CZagrobelny/new_sanctuary_asylum#98]
Steps to Reproduce:
- Log in as Community Admin
- Go to Activities
- Create Activity
- Fill out all fields except one of the required ones (e.g., Type)
- Click Save, see error about missing required field
- Update your form to provide missing field's information
- Click Save
- Activity is now saved in the database but will not appear on your calendar (even after refresh / cache clear)

@CZagrobelny please let me know if you need any other info or if I've misunderstood something about how this should work!

**Comment by acatxnamedvirtue** [comment]
I'll take this one

**Comment by acatxnamedvirtue** [comment]
I created three events the way you described above:

One event was for tomorrow: This one actually showed up immediately.

One event was for today an hour ago: This one did not show up. I'm thinking this is probably intentional, since no other previous activities in the DB show up 

One event was for today in the future: This one did not show up, I'll investigate

**Comment by acatxnamedvirtue** [comment]
Ahh, okay, so the "Type" must be one of the "NON_ACCOMPANIMENT_ELIGIBLE_EVENTS" to show up on the activities calendar. That is, it must be one of these:

filing_asylum_application
asylum_granted
filing_work_permit
detained
guardianship_requested
sijs_special_findings_form_finished
sijs_application_submitted
sijs_granted
sijs_denied
change_of_venue_submitted
foia_request_submitted
foia_recieved

**Comment by acatxnamedvirtue** [comment]
@CZagrobelny as long as this behavior is intended, I think we can close this issue. If it is not intended, please advise what the behavior should actually be and I'll implement it

**Comment by CZagrobelny** [comment]
@acatxnamedvirtue that is totally it!  Thank you for identifying that, I will close the issue!

**Comment by hwigmore** [comment]
ah! thanks @acatxnamedvirtue for digging into this! sorry for the false alarm.
